---
commitizen:
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: v$version
  changelog_incremental: true
  update_changelog_on_bump: true
  version_provider: pep621
  version_scheme: semver
  changelog_increment_filename: CHANGELOG.md
  bump_message: "[skip ci]bump: update version $current_version → $new_version"
  message_template: "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
  example: "feature: this feature enable customize through config file"
  schema: "<type>: <body>"
  schema_pattern: "(fix|feat|docs|refactor|perf|test|style|ci|build|break):(\\s.*)"
  bump_pattern: "^(fix|feat|docs|refactor|perf|test|style|ci|build|break)"
  bump_map:
    break: MAJOR
    fix: PATCH
    feat: MINOR
    docs: PATCH
    refactor: PATCH
    perf: PATCH
    test: PATCH
    style: PATCH
    ci: PATCH
    build: PATCH
  change_type_order:
    - "BREAKING CHANGE"
    - "feat"
    - "fix"
    - "docs"
    - "refactor"
    - "perf"
    - "test"
    - "style"
    - "ci"
    - "build"
  version_files:
    - "pyproject.toml:^version"
