variables:
  UV_VERSION: "0.6"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy  # GitLab CI build dir requires copy mode

.default_git_setup: &default_git_setup
  - apt-get update && apt-get install -y git
  - git remote set-url origin "https://${CI_GIT_USERNAME}:${CI_GIT_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"
  - git fetch origin
  - git fetch --tags --unshallow
  - git checkout -B "$CI_DEFAULT_BRANCH" "origin/$CI_DEFAULT_BRANCH"
  - ls -al .git || echo "⚠️ Dossier .git non présent"

.default_image: &default_image ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER

workflow:
  rules:
    - if: ($CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH )

stages:
  - build-devcontainer
  - check
  - test
  - release
  - build-project
  - deploy

# Lint + Format
python_lint:
  stage: check
  image: *default_image
  script:
    - uv run --native-tls --group dev ruff check .

python_format:
  stage: check
  image: *default_image
  script:
    - uv run --native-tls --group dev ruff format --check .

# Tests unitaires
coverage:
  stage: test
  image: *default_image
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache: &default_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /root/.cache/uv
      - .venv/
  script:
    - uv run --native-tls --group dev pytest
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


# Test the retro-compatibility of the package again multiple python version
pytest:
  stage: test
  image: *default_image
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache: *default_cache
  script:
    - uv run --native-tls --python ${VERSION} --group dev pytest
  parallel:
    matrix:
      - VERSION: {{ cookiecutter.python_matrix }}


# Versioning + changelog (release)
release:
  stage: release
  image: *default_image
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  before_script: *default_git_setup
  script:
    - git config --global user.name "CI Gitlab"
    - git config --global user.email "ci@gitlab.com"
    - uv run cz bump --yes --changelog
    - git push origin "$CI_DEFAULT_BRANCH"
    - git push --tags
  needs:
    - 'python_format'
    - 'python_lint'
    - coverage
    - pytest


# Build the Docker image (API) with OCI labels
build-docker-api:
  stage: build-project
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - docker build \
        --build-arg BUILD_VERSION=$(cat VERSION) \
        --build-arg BUILD_REVISION=$CI_COMMIT_SHA \
        --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
        --target api \
        -t api:latest \
        -f dockerfiles/Dockerfile .

