services:

  python-app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: {{ cookiecutter.repo_name }}-pythonserver
    ports:
      - "8000:8000"
    command: uvicorn {{ cookiecutter.repo_name }}.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - {{ cookiecutter.repo_name }}-network
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./pyproject.toml
          target: /app/pyproject.toml
        - action: rebuild
          path: ./Dockerfile

networks:
  {{ cookiecutter.repo_name }}-network:
    driver: bridge
    name: {{ cookiecutter.repo_name }}-network
