# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
from datetime import date

# -- Project information -----------------------------------------------------

project = "{{ cookiecutter.project_name }}"
copyright = f"{date.today().year}, {{ cookiecutter.author_name }}"
author = "{{ cookiecutter.author_name }}"



# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.graphviz",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.viewcode",
    "sphinx_git",
    "sphinx_inline_tabs",
    "sphinxcontrib.mermaid",
    "sphinx_copybutton",
    "sphinx_favicon",
    # "sphinx_last_updated_by_git",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx_simplepdf",
    "sphinxcontrib.youtube",
    "sphinxcontrib.googleanalytics",
    "myst_parser",
]

# GA ID
googleanalytics_id = "G-XXXXXXXX"

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = [".rst", ".md"]

# Delete Warning dupplicate label
suppress_warnings = ["autosectionlabel.*"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "*/README.rst",
    "README.rst",
    "**.ipynb_checkpoints",
    "*/ReadMe.MD",
    "ReadMe.MD",
    "*/ReadMe.MD",
    ".venv",
    ".gitlab",
    "CHANGELOG.md",
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = "{{ cookiecutter.sphinx_theme }}"

{% if cookiecutter.sphinx_theme == 'furo' -%}
html_theme_options = {
    "top_of_page_button": "edit",
    "source_edit_link": "https://gitlab.com/xxxx/knowledge/edit/main/{filename}",
}
{% else -%}
html_theme_options = {}
{% endif -%}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = []
html_static_path = ["_static"]
html_extra_path = ["staticwebapp.config.json"]

# By default, generated HTML <title> has the value project release documentation. E.g. Tech writer at work 1.0 documentation.
# If you don’t have conf.py’s release set, it is e.g., Tech writer at work  documentation (please note two spaces among “work” and “documentation”).
# If you don’t like word “documentation” or two-space issue, you have to set custom title in html_title conf.py option. For example, let’s set it to the same value as a project option.
html_title = project

# Code examples are highlighted by default syntax highlight language, if not configured otherwise for a particular example. Sphinx default syntax highlighting mode is 'python3'.
# Maybe as Sphinx is mainly used in Python projects, it is reasonable value, but I personally almost always change it to ''none'' that turns off syntax highlighting
highlight_language = "none"


# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = ".aspx"


favicons = [
    {
        "href": "emlyon_logo.png"
    },  # => use `_static/icon.svg`
]

html_use_index = True

#
# html_theme_options = {
#     "announcement": "<em>Announcement</em>: This is the test launch of the knowledge center",
# }

{% raw %}
# -- Options LaTeX ------------------------------------------------------------

# Configuration utilisateur
# Input
folder_template = "./_static/pdf"
logo_filename = "logo.png"
cover_background_filename = "background.png"
page_background_filename = "page-background.pdf"
# Output
latex_output_filename = "astrodata_documentation.tex"
document_subtitle = "PDF Documentation"

# Variables globales
today = date.today().strftime("%B %d, %Y")
latex_logo = os.path.join(folder_template, logo_filename)
cover_background = os.path.join(folder_template, cover_background_filename)
page_background = os.path.join(folder_template, page_background_filename)

latex_additional_files = [latex_logo, cover_background, page_background]

latex_engine = "xelatex"
master_doc = "index"
latex_theme = "manual"
latex_documents = [("index", latex_output_filename, project, author, "howto")]

latex_elements = {
    "sphinxsetup": r"""
        TitleColor={HTML}{3E71D4},
        InnerLinkColor={HTML}{3E71D4},
        OuterLinkColor={HTML}{3E71D4},
        VerbatimColor={HTML}{F7F7F7},
        VerbatimBorderColor={HTML}{E0E0E0}
    """,
    "fontpkg": r"""
        \usepackage{fontspec}
        \setmainfont{DejaVu Sans}
        \setsansfont{DejaVu Sans}
        \setmonofont{DejaVu Sans}
    """,
    "preamble": r"""
        %%% --- Variables dynamiques depuis conf.py ---
        \newcommand{\docTitle}{"""
    + project
    + r"""}
        \newcommand{\docAuthor}{"""
    + author
    + r"""}
        \newcommand{\docDate}{"""
    + today
    + r"""}
        \newcommand{\docSubtitle}{"""
    + document_subtitle
    + r"""}

        %%% --- Fichiers graphiques dynamiques ---
        \newcommand{\docLogo}{"""
    + logo_filename
    + r"""}
        \newcommand{\docCoverBg}{"""
    + cover_background_filename
    + r"""}
        \newcommand{\docPageBg}{"""
    + page_background_filename
    + r"""}

        %%% --- Packages ---
        \usepackage{graphicx}
        \graphicspath{{./}}
        \usepackage{xcolor}
        \usepackage{fancyhdr}
        \usepackage{titlesec}
        \usepackage{hyperref}
        \usepackage{eso-pic}
        \usepackage{geometry}
        \usepackage{etoolbox}

        %%% --- Palette corporate ---
        \definecolor{CorpPrimary}{HTML}{E2001A}
        \definecolor{CorpBlack}{HTML}{000000}
        \definecolor{CorpGrey}{HTML}{666666}

        \hypersetup{
          colorlinks=true,
          linkcolor=CorpPrimary,
          urlcolor=CorpPrimary,
          citecolor=CorpPrimary
        }

        %%% --- Marges ---
        \geometry{
          a4paper,
          top=3cm,    % marge en haut
          bottom=2.2cm,
          left=2.2cm,
          right=2.2cm
        }

        %%% --- Styles de titres ---
        \titleformat{\section}{\Large\bfseries\color{CorpBlack}}{\thesection}{0.6em}{}
        \titleformat{\subsection}{\large\bfseries\color{CorpBlack}}{\thesubsection}{0.6em}{}
        \titleformat{\subsubsection}{\normalsize\bfseries\color{CorpBlack}}{\thesubsubsection}{0.6em}{}

        %%% --- En-têtes / pieds (style fancy) ---
        \fancypagestyle{fancy}{%
          \fancyhf{}
          % Header : titre centré + logo à droite
          \fancyhead[C]{\color{CorpGrey} \docTitle}
          % Footer : date à gauche, auteur au centre, numéro de page à droite
          \fancyfoot[L]{\color{CorpGrey} \docDate}
          \fancyfoot[C]{\color{CorpGrey} \docAuthor}
          \fancyfoot[R]{\color{CorpGrey} \thepage}
          % Règles
          \renewcommand{\headrulewidth}{0.4pt}
          \renewcommand{\footrulewidth}{0.4pt}
          \renewcommand{\headrule}{\hbox to\headwidth{\color{CorpGrey}\leaders\hrule height \headrulewidth\hfill}}
          \renewcommand{\footrule}{\hbox to\headwidth{\color{CorpGrey}\leaders\hrule height \footrulewidth\hfill}}
        }

        %%% --- Style plain = identique à fancy ---
        \fancypagestyle{plain}{%
          \fancyhf{}
          \fancyhead[C]{\color{CorpGrey} \docTitle}
          \fancyhead[R]{\includegraphics[height=1cm]{\docLogo}}
          \fancyfoot[L]{\color{CorpGrey} \docDate}
          \fancyfoot[C]{\color{CorpGrey} \docAuthor}
          \fancyfoot[R]{\color{CorpGrey} \thepage}
          \renewcommand{\headrulewidth}{0.4pt}
          \renewcommand{\footrulewidth}{0.4pt}
          \renewcommand{\headrule}{\hbox to\headwidth{\color{CorpGrey}\leaders\hrule height \headrulewidth\hfill}}
          \renewcommand{\footrule}{\hbox to\headwidth{\color{CorpGrey}\leaders\hrule height \footrulewidth\hfill}}
        }

        %%% --- Forcer fancy partout ---
        \makeatletter
        \AtBeginDocument{%
          \pagestyle{fancy}
          \let\ps@plain\ps@fancy
        }
        \makeatother

        %%% --- Saut de page avant chaque section ---
        \preto\section{\clearpage\thispagestyle{fancy}}
        \preto\subsection{\thispagestyle{fancy}}
        \preto\subsubsection{\thispagestyle{fancy}}

        %%% --- Page de garde personnalisée ---
        \makeatletter
        \renewcommand{\sphinxmaketitle}{%
          \begin{titlepage}
            \AddToShipoutPictureBG*{%
              \AtPageLowerLeft{\includegraphics[width=\paperwidth,height=\paperheight]{\docCoverBg}}%
            }
            \thispagestyle{empty}
            \vspace*{2cm}
            \begin{center}
              \includegraphics[height=1.6cm]{\docLogo}\par\vspace{1.5cm}
              {\Huge\bfseries\color{CorpBlack} \docTitle \par}\vspace{0.75cm}
              {\large\color{CorpGrey} \docAuthor \par}\vspace{0.3cm}
              {\large\color{CorpGrey} \docDate \par}
              \vspace{1.5cm}
              \rule{\linewidth}{0.6pt}\par
              \vspace{0.5cm}
              {\large\color{CorpPrimary} \docSubtitle \par}
            \end{center}
            \vfill
          \end{titlepage}

          % Fond global pour les pages suivantes
          \AddToShipoutPictureBG{%
            \AtPageLowerLeft{\includegraphics[width=\paperwidth,height=\paperheight]{\docPageBg}}%
          }

          \pagestyle{fancy}
          \thispagestyle{fancy}
        }
        \makeatother
    """,
}


# -- Options for simple pdf output --------------------------------
version = "1.0"

simplepdf_debug = False

simplepdf_file_name = "astrodata-knowledge-center.pdf"

simplepdf_vars = {
    # 'cover-overlay': 'rgba(26, 150, 26, 0.7)',
    # 'primary-opaque': 'rgba(26, 150, 26, 0.7)',
    "cover-bg": "url(cover-bg.jpg) no-repeat center",
    "primary": "#E2001A",
    "secondary": "#000000",
    "cover": "#ffffff",
    "white": "#ffffff",
    "links": "#E2001A",
    "top-left-content": "counter(page)",
    # 'top-center-content': '',
    "top-right-content": "string(heading)",
    # 'bottom-left-content': 'counter(page)',
    "bottom-center-content": '"Data Knowledge Center Documentation"',
    # 'bottom-right-content': 'string(heading)',
}
{% endraw %}
